### ISSUE TITLE
Fragile Gimmick and the Sky Stages temporary game freeze

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#88] opened 2024-05-24 06:02 UTC
If one destroys a block causing a block above to fall to the abyss (through open bottom of the stage) on stages Sky Islands, Dreamful Beachscape, Windy Islands or Dreamscape Hubworld with the Fragile gimmick, **the game will freeze for 2.5 seconds.**

1. Start a Run with either of the 4 Tilesets and gimmick "Fragile" locked in config.json:
```
"tileset":"Sky Islands"
"tileset":"Dreamful Beachscape"
"tileset":"Windy Islands"
"tileset":"Dreamscape Hubworld"
"gimmick":"Fragile"
```
2. Head towards the bottom of the stage, but be careful not to fall
3. Break a tile with Nemesis or Invidia on terrain floating above the abyss
4. The tile above tries to fall through the abyss and the game freezes for 2.5 seconds.

Versions 1.44.0.0 and prior. (Please note: Prior versions do not have Windy Islands or Dreamscape Hubworld)

**Comment by TrashboxBobylev** [comment] 2024-05-26 18:10
Fixed in 1.44.1 (the cause of lag was that falling block shift check didn't check for map limits, so it waited until int overflows and check is valid).

**Closed by TrashboxBobylev** 2024-05-26 18:10 UTC
Labels: bug, 1.44
